spring.application.name=api-flowable-labs

# DataSource - PostgreSQL
spring.datasource.url=jdbc:postgresql://${PJE_DS_DB_HOST:localhost}:${PJE_DS_DB_PORT:5432}/${PJE_DS_DB_NAME:pje}?sslmode=require&currentSchema=client,core,jt,criminal,public,acl
spring.datasource.username=${PJE_DS_DB_USER:postgres}
spring.datasource.password=${PJE_DS_DB_PASS:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# Connection pool (HikariCP)
spring.datasource.hikari.minimum-idle=${PJE_DS_MIN_POOL_SIZE:1}
spring.datasource.hikari.maximum-pool-size=${PJE_DS_MAX_POOL_SIZE:10}
spring.datasource.hikari.connection-test-query=select 1
spring.datasource.hikari.connection-init-sql=set search_path=client,core,jt,criminal,public,acl
spring.datasource.hikari.read-only=true

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Flowable
management.endpoints.web.exposure.include=flowable
